#!/bin/sh

G1='\033[0;32m'
G2='\033[1;32m'
Y1='\033[1;33m' 
Y2='\033[0;33m'
R1='\033[1;31m'
R2='\033[0;31m'
NC='\033[0m'

echo ""
echo "${G1} TB                                   ${R2} BT  "
echo "${G1}  TB                                  ${R2}BT   "
echo "${G2}   TB                                ${R2}BT    "
echo "${G2}    TB      ${G1}bbbbbb${R1}bbbbbb${R2}bbbbbb      ${R2}BT     "
echo "${Y1}     TB    ${G1}bbbbb${R1}bbbbbbb${R2}bbbbbbbb    ${R2}BT      "
echo "      ${Y1}TB${G1}BBBBBB${R1}BBBBBBBB${R2}BBBBBBBBBBBBBT       "
echo "     ${Y1}d${G1}BBBBBB${R1}BBBBBBBBB${R2}BBBBBBBBBBBBBBBb      "
echo "   ${Y1}d${G1}BBBBBBB${R1}BBBBBBBBB${R2}BBBBBBBBBBBBBBBBBBb    "
echo "  ${G1}d${G1}BBBBBB${R1}BBBBBBBBB${R2}BBBBBBBBBBBBBBBBBBBBBb   "
echo " ${G1}d${G1}BBBB${R1}Bb  dB${R2}BBBBBBBBBBBBBBBBBb  dBBBBBBBb  "
echo " ${G1}d${G1}BB${R1}BBBb${R2}  dBBBBBBBBBBBBBBBBBBb  dBBBBBBBb  "
echo " ${G1}M${G1}${R1}BBBBBB${R2}bbBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBM  "
echo " ${R1}MBBBB${R2}BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBM  "

echo "${R1}                  _           _     _  "
echo "${R1}                 | |         (_)   | | "
echo "${R1}   __ _ _ __   __| |_ __ ___  _  __| | "
echo "${G2}  / _\` | '_ \\ / _\` | '__/ _ ${R1}\\| |/ _\` | "
echo "${G2} | (_| | | | | (_| | | | (_) | | (${R1}_| | "
echo "${Y1}  \\__,_|_| |_|\\__,_|_|  \\___/|_|\\__,_| ${NC}"
echo ""